name: Backup

on:
  schedule:
    - cron: "30 2 * * *"
  repository_dispatch:
    types: [backup]

jobs:
  backup:
    runs-on: ubuntu-latest

    env:
      VM_USER_NAME: frederikskaj2
      VM_HOST_NAME: lokaler.frederikskaj2.dk
      PATH: /var/lokaler/
      FILE_NAME: Reservations.db

    steps:
      - name: Get SSH key
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: ~/.ssh/id_rsa
          contents: ${{ secrets.VM_SSH_KEY }}
          write-mode: overwrite
      - name: Copy database
        run: sshpass -p '${{ env.VM_SSH_PASSWORD }}' scp -o StrictHostKeyChecking=no ${{ env.VM_USER_NAME }}@${{ env.VM_HOST_NAME }}:${{ env.PATH }}${{ env.FILE_NAME }} .
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Database
          path: ${{ env.FILE_NAME }}
