name: Backup

on:
  schedule:
    - cron: "30 2 * * *"
  repository_dispatch:
    types: [backup]

jobs:
  backup:
    runs-on: ubuntu-latest

    env:
      VM_HOST_NAME: lokaler.frederikskaj2.dk
      FILE_PATH: /var/lokaler/
      FILE_NAME: Reservations.db

    steps:
      - name: Get HOME
        run: echo "::set-env name=HOME::$(ls -d ~)"
      - name: Install sshpass
        run: sudo apt-get install sshpass
      - name: Get SSH key
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: ${{ env.HOME }}/.ssh/id_rsa
          contents: ${{ secrets.VM_SSH_KEY }}
          write-mode: overwrite
      - name: Fix permissions
        run: |
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
      - name: Copy database
        run: sshpass -p '${{ secrets.VM_SSH_PASSWORD }}' -P assphrase scp -o StrictHostKeyChecking=no ${{ secrets.VM_USER_NAME }}@$VM_HOST_NAME:$FILE_PATH$FILE_NAME .
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Database
          path: ${{ env.FILE_NAME }}
