name: Build and deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - name: Get source code
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Install WASM tools
        run: dotnet workload install wasm-tools

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish Server --configuration Release --no-build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Server
          path: Server/bin/Release/net9.0/publish/
          retention-days: 7

  deploy-to-test:
    name: Deploy to test

    needs: build

    runs-on: ubuntu-latest

    environment: Test

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: Server

      - name: Deploy to Azure
        uses: Azure/webapps-deploy@v3.0.1
        with:
          app-name: lokaler-test
          publish-profile: ${{secrets.AZURE_WEBAPP_PUBLISH_PROFILE}}

      - name: Get source code
        uses: actions/checkout@v4

      - name: Get timestamp
        run: echo "TIMESTAMP=`TZ=Europe/Copenhagen date +"%d-%m-%Y %H:%M"`" >> $GITHUB_ENV

      - name: Get short commit SHA
        run: echo "COMMITSHORT=`echo ${{github.sha}} | cut -c-10`" >> $GITHUB_ENV

      - name: Post to Teams
        run: >
            Get-Content -Path .github/workflows/deploy-to-test-success.json -Raw
            | ForEach-Object -Process { $_ -creplace 'TIMESTAMP', '${{env.TIMESTAMP}}' -creplace 'COMMITSHORT', '${{env.COMMITSHORT}}' -creplace 'COMMITLONG', '${{github.sha}}' }
            | Invoke-RestMethod -Uri '${{secrets.BUILD_SUCCESS_WEBHOOK}}' -Method Post -Headers @{ 'Content-Type' = 'application/json' }
        shell: pwsh

  deploy-to-production:
    name: Deploy to production

    needs: deploy-to-test

    runs-on: ubuntu-latest

    environment: Production

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: Server

      - name: Deploy to Azure
        uses: Azure/webapps-deploy@v3.0.1
        with:
          app-name: lokaler
          publish-profile: ${{secrets.AZURE_WEBAPP_PUBLISH_PROFILE}}

      - name: Get source code
        uses: actions/checkout@v4

      - name: Get timestamp
        run: echo "TIMESTAMP=`TZ=Europe/Copenhagen date +"%d-%m-%Y %H:%M"`" >> $GITHUB_ENV

      - name: Get short commit SHA
        run: echo "COMMITSHORT=`echo ${{github.sha}} | cut -c-10`" >> $GITHUB_ENV

      - name: Post to Teams
        run: >
            Get-Content -Path .github/workflows/deploy-to-production-success.json -Raw
            | ForEach-Object -Process { $_ -creplace 'TIMESTAMP', '${{env.TIMESTAMP}}' -creplace 'COMMITSHORT', '${{env.COMMITSHORT}}' -creplace 'COMMITLONG', '${{github.sha}}' }
            | Invoke-RestMethod -Uri '${{secrets.BUILD_SUCCESS_WEBHOOK}}' -Method Post -Headers @{ 'Content-Type' = 'application/json' }
        shell: pwsh
