name: Build and deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - name: Get source code
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.401

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish Server --configuration Release --no-build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Server
          path: Server/bin/Release/net6.0/publish/
          retention-days: 7

  deploy-to-test:
    name: Deploy to production
    
    needs: build

    runs-on: ubuntu-latest

    environment: Production

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: Server

      - name: Deploy to Azure
        uses: Azure/webapps-deploy@v2
        with:
          app-name: lokaler-test
          publish-profile: ${{secrets.AZURE_WEBAPP_PUBLISH_PROFILE}}

      - name: Get source code
        uses: actions/checkout@v3
        
      - name: Get timestamp
        run: echo "TIMESTAMP=`TZ=Europe/Copenhagen date +"%d-%m-%Y %H:%M"`" >> $GITHUB_ENV

      - name: Get short commit SHA
        run: echo "COMMITSHORT=`echo ${{github.sha}} | cut -c-10`" >> $GITHUB_ENV

      - name: Post to Teams
        run: >
          sed -e 's/TIMESTAMP/${{env.TIMESTAMP}}/' -e s/COMMITSHORT/${{env.COMMITSHORT}}/ -e s/COMMITLONG/${{github.sha}}/ .github/workflows/deploy-to-test-success.json | curl -d @- -H 'Content-Type: application/json' -X POST ${{secrets.BUILD_SUCCESS_WEBHOOK}}

  deploy-to-production:
    name: Deploy to production
    
    needs: deploy-to-test

    runs-on: ubuntu-latest

    environment: Test

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: Server

      - name: Deploy to Azure
        uses: Azure/webapps-deploy@v2
        with:
          app-name: lokaler
          publish-profile: ${{secrets.AZURE_WEBAPP_PUBLISH_PROFILE}}

      - name: Get source code
        uses: actions/checkout@v3
        
      - name: Get timestamp
        run: echo "TIMESTAMP=`TZ=Europe/Copenhagen date +"%d-%m-%Y %H:%M"`" >> $GITHUB_ENV

      - name: Get short commit SHA
        run: echo "COMMITSHORT=`echo ${{github.sha}} | cut -c-10`" >> $GITHUB_ENV

      - name: Post to Teams
        run: >
          sed -e 's/TIMESTAMP/${{env.TIMESTAMP}}/' -e s/COMMITSHORT/${{env.COMMITSHORT}}/ -e s/COMMITLONG/${{github.sha}}/ .github/workflows/deploy-to-production-success.json | curl -d @- -H 'Content-Type: application/json' -X POST ${{secrets.BUILD_SUCCESS_WEBHOOK}}
